import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';
const root=path.resolve(import.meta.dirname,'..');process.chdir(root);
const audio=process.argv[2];if(!audio)throw new Error('Pass the complete preserved HyperFrames audio mix.');
const captions=JSON.parse(fs.readFileSync('caption_groups.json','utf8'));
const stamp=t=>{let n=Math.round(t*100);const h=Math.floor(n/360000);n%=360000;const m=Math.floor(n/6000);n%=6000;return `${h}:${String(m).padStart(2,'0')}:${String(Math.floor(n/100)).padStart(2,'0')}.${String(n%100).padStart(2,'0')}`;};
const header=`[Script Info]\nTitle: Anghkooey final audio-aligned captions\nScriptType: v4.00+\nPlayResX: 1920\nPlayResY: 1080\nWrapStyle: 2\nScaledBorderAndShadow: yes\n\n[V4+ Styles]\nFormat: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\nStyle: Default,Satoshi Film,46,&H00DFEEF4,&H00DFEEF4,&H000F0805,&H000F0805,0,0,0,0,100,100,0,0,3,12,0,2,125,125,54,1\n\n[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n`;
fs.writeFileSync('captions.ass',header+captions.map(c=>`Dialogue: 0,${stamp(c.start)},${stamp(c.end)},Default,,0,0,0,,${c.text.replace(/[{}]/g,'')}`).join('\n')+'\n');
if(process.argv.includes('--captions-only'))process.exit(0);
const recovery=JSON.parse(fs.readFileSync('verification/recovery.json','utf8'));if(recovery.frames!==10500)throw new Error('All 10500 frames must be recovered before encoding.');
const measure=spawnSync('ffmpeg',['-hide_banner','-nostats','-i',audio,'-af','loudnorm=I=-16:TP=-1.5:LRA=11:print_format=json','-f','null','-'],{encoding:'utf8',maxBuffer:4*1024*1024});if(measure.status!==0)throw new Error(`Loudness measurement failed: ${measure.status}`);
const m=JSON.parse(measure.stderr.match(/\{\s*"input_i"[\s\S]*?\}/)[0]);fs.writeFileSync('verification/input-loudness.json',JSON.stringify(m,null,2));
const norm=`loudnorm=I=-16:TP=-1.5:LRA=11:measured_I=${m.input_i}:measured_TP=${m.input_tp}:measured_LRA=${m.input_lra}:measured_thresh=${m.input_thresh}:offset=${m.target_offset}:linear=true:print_format=json`;
const output='anghkooey-demo-FINAL-1080p60.mp4';
console.log('Encoding final authentic HyperFrames frames, corrected caption rail, original audio mix.');
const result=spawnSync('ffmpeg',['-y','-hide_banner','-framerate','60','-start_number','0','-i','verification/recovery-frames/frame_%06d.jpg','-i',audio,'-map','0:v:0','-map','1:a:0','-vf','scale=in_range=full:out_range=limited,format=yuv420p,drawbox=x=0:y=930:w=iw:h=150:color=0x05080f:t=fill,ass=filename=captions.ass:fontsdir=assets/fonts,setparams=range=limited','-af',norm,'-c:v','libx264','-preset','fast','-crf','16','-threads','4','-pix_fmt','yuv420p','-r','60','-c:a','aac','-b:a','256k','-ar','48000','-t','175','-movflags','+faststart',output],{stdio:'inherit'});
if(result.status!==0)throw new Error(`Final encode failed: ${result.status}`);
const info=JSON.parse(spawnSync('ffprobe',['-v','error','-show_streams','-show_format','-of','json',output],{encoding:'utf8'}).stdout);
const video=info.streams.find(x=>x.codec_type==='video');const sound=info.streams.find(x=>x.codec_type==='audio');
if(video.width!==1920||video.height!==1080||video.avg_frame_rate!=='60/1'||video.codec_name!=='h264'||sound?.codec_name!=='aac'||Number(info.format.duration)>180)throw new Error('Delivery format verification failed.');
fs.writeFileSync('verification/final-probe.json',JSON.stringify(info,null,2));console.log('DELIVERY_ENCODE_COMPLETE:',output,info.format.duration,'seconds');
